### ISSUE TITLE
updating use custom value for one column

### ISSUE THREAD

**Issue by enapupe** [felixmosh/knex-on-duplicate-update#4]
Hey there, thanks for building this.

I'm facing a situation where I'll have to set a specific value for the update values, instead of doing a full `column=values(column)`, for one of the columns i'd like to manually set the new value in case it already exists, so it would be something like `column=values(column), columnB='X'`

Do you think this is a problem this plugin could address? 
~For what I see, this would have to be a breaking change as it currently consumes ALL params passed to the fn.~

Thanks

**Comment by felixmosh** [comment]
Thanx for the issue.
I've intentionally made this lib simple as possible so whenever there is a feature request it will be pushed by community.

You Feature request makes sense, I will review your PR :]
